services:
  expense-tracker-database:
    build:
      context: expense-tracker-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:
