services:
  expense-tracker-database-test:
    build:
      context: expense-tracker-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432"

volumes:
  postgres_data: