spring:
  application:
    name: pmr-expense-tracker

  flyway:
    enabled: true
    locations: db/migration
    schemas: public
    baselineOnMigrate: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/expense_tracker
    username: postgres
    password: postgres

    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
